from llama_index.core import PromptTemplate

default_prompt_str = "{prompt}"

default_template = PromptTemplate(default_prompt_str)

test_target_repository_name = "RepoAgent"

test_target_repository_language = "Python 3.12"

test_problem_statement = """
{'title': 'maximum recursion depth exceeded in comparison', 'body': 'Receiving the following error when : \r\n2024-07-09 12:48:43.996 | SUCCESS  | repo_agent.log:set_logger_level_from_config:74 - Log level set to INFO!\r\nparsing parent relationship:   0%|                                                                                      parsing parent relationship: 100%|█████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 8184.01it/s]\r\nLoading MetaInfo: /home/jovyan/work/Documentation/Arya/wiki/hierarchy_files\r\nMetaInfo is Refreshed and Saved\r\n2024-07-09 12:48:44.015 | INFO     | repo_agent.runner:first_generate:104 - Starting to generate documentation\r\nparsing bidirectional reference:   0%|                                                                                   | 0/2 [00:00<?, ?it/s]2024-07-09 12:48:44.198 | INFO     | repo_agent.doc_meta_info:find_all_referencer:293 - Error occurred: `column` parameter (6) is not in a valid range (0-0) for line 205 (\'\\n\').\r\n2024-07-09 12:48:44.198 | INFO     | repo_agent.doc_meta_info:find_all_referencer:294 - Parameters: variable_name=Embed, file_path=wikiv1.py, line_number=205, column_number=6\r\n2024-07-09 12:48:44.208 | INFO     | repo_agent.doc_meta_info:find_all_referencer:293 - Error occurred: `line` parameter is not in a valid range.\r\n2024-07-09 12:48:44.208 | INFO     | repo_agent.doc_meta_info:find_all_referencer:294 - Parameters: variable_name=create_collection, file_path=wikiv1.py, line_number=284, column_number=4\r\nparsing bidirectional reference:  50%|█████████████████████████████████████▌                                     | 1/2 [00:00<00:00,  5.17it/s]2024-07-09 12:48:44.212 | INFO     | repo_agent.doc_meta_info:find_all_referencer:293 - Error occurred: `column` parameter (6) is not in a valid range (0-0) for line 205 (\'\\n\').\r\n2024-07-09 12:48:44.213 | INFO     | repo_agent.doc_meta_info:find_all_referencer:294 - Parameters: variable_name=Embed, file_path=.ipynb_checkpoints/wikiv1-checkpoint.py, line_number=205, column_number=6\r\n2024-07-09 12:48:44.220 | INFO     | repo_agent.doc_meta_info:find_all_referencer:293 - Error occurred: `line` parameter is not in a valid range.\r\n2024-07-09 12:48:44.220 | INFO     | repo_agent.doc_meta_info:find_all_referencer:294 - Parameters: variable_name=create_collection, file_path=.ipynb_checkpoints/wikiv1-checkpoint.py, line_number=284, column_number=4\r\nparsing bidirectional reference: 100%|███████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.74it/s]\r\nparsing topology task-list:   0%|                                                                                       | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):\r\n  File "/home/jovyan/work/repoagent/RepoAgent/repo_agent/main.py", line 312, in <module>\r\n    cli()\r\n  File "/opt/conda/envs/repoenv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__\r\n    return self.main(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "/opt/conda/envs/repoenv/lib/python3.11/site-packages/click/core.py", line 1078, in main\r\n    rv = self.invoke(ctx)\r\n         ^^^^^^^^^^^^^^^^\r\n  File "/opt/conda/envs/repoenv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "/opt/conda/envs/repoenv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "/opt/conda/envs/repoenv/lib/python3.11/site-packages/click/core.py", line 783, in invoke\r\n    return __callback(*args, **kwargs)\r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "/home/jovyan/work/repoagent/RepoAgent/repo_agent/main.py", line 260, in run\r\n    runner.run()\r\n  File "/home/jovyan/work/repoagent/RepoAgent/repo_agent/runner.py", line 240, in run\r\n    self.first_generate() # 如果是第一次做文档生成任务，就通过first_generate生成所有文档\r\n    ^^^^^^^^^^^^^^^^^^^^^\r\n  File "/home/jovyan/work/repoagent/RepoAgent/repo_agent/runner.py", line 106, in first_generate\r\n    task_manager = self.meta_info.get_topology(\r\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "/home/jovyan/work/repoagent/RepoAgent/repo_agent/doc_meta_info.py", line 619, in get_topology\r\n    task_manager = self.get_task_manager(\r\n                   ^^^^^^^^^^^^^^^^^^^^^^\r\n  File "/home/jovyan/work/repoagent/RepoAgent/repo_agent/doc_meta_info.py", line 577, in get_task_manager\r\n    if task_available_func(child) and (child not in deal_items):\r\n                                       ^^^^^^^^^^^^^^^^^^^^^^^\r\n  File "<string>", line 4, in __eq__\r\n  File "<string>", line 4, in __eq__\r\n  File "<string>", line 4, in __eq__\r\n  [Previous line repeated 851 more times]\r\nRecursionError: maximum recursion depth exceeded in comparison\r\nparsing topology task-list:  90%|███████████████████████████████████████████████████████████████████████        | 9/10 [00:00<00:00, 34.28it/s]\r\n', 'author': 'Major-wagh'}
"""
